---
- name: Update web servers
  hosts: "{{ target }}"
  remote_user: ubuntu

  vars_prompt:
    - name: target
      prompt: enter the hostname which you might have mentioned in host file
      private: no

    - name: domain
      prompt: please enter the domain which will be serving the requests
      private: no

    - name: envtype
      prompt: please enter the env file to copy, we are appending to .env, hence value can be -staging etc
      private: no

  tasks:
    - name: Clone biap-client-node-js
      git:
        repo: "https://github.com/ONDC-Official/biap-client-node-js.git"
        dest: "/home/ubuntu/biap-client-node-js"
        version: "master"

    - name: Clone biap ui
      git:
        repo: "https://github.com/Abhi-ONDC/biap-app-ui-front.git"
        dest: "/home/ubuntu/biap-app-ui-front"
        version: "master"

    - name: Clone biap-igm-node-js
      git:
        repo: "https://github.com/ONDC-Official/biap-igm-node-js.git"
        dest: "/home/ubuntu/biap-igm-node-js"
        version: "main"

    - name: Clone py ondc protocol
      git:
        repo: "https://github.com/sharmasahil0331/py-protocol-layer"
        dest: "/home/ubuntu/py-ondc-protocol"
        version: "master"

    - name: Clone biap-bugzilla-service
      git:
        repo: "https://github.com/ONDC-Official/biap-bugzilla-service"
        dest: "/home/ubuntu/biap-bugzilla-service"
        version: "main"

    - name: Copy config directory
      copy:
        src: "{{ playbook_dir }}/../biap-client-node-js/config"
        dest: "/home/ubuntu/biap-client-node-js/"
        owner: "ubuntu"
        group: "ubuntu"
        mode: "0755"

    - name: Copy config directory for igm
      copy:
        src: "{{ playbook_dir }}/../biap-igm-node-js/config"
        dest: "/home/ubuntu/biap-igm-node-js/"
        owner: "ubuntu"
        group: "ubuntu"
        mode: "0755"

    - name: copy Dockerfile without SSL as dockerfile in biap-app-ui-front
      copy:
        src: "{{ playbook_dir }}/../biap-app-ui-front/Dockerfile"
        dest: "/home/ubuntu/biap-app-ui-front/Dockerfile"
        owner: "ubuntu"
        group: "ubuntu"
        mode: "0755"

    - name: copy nginx conf with ssl
      copy:
        src: "{{ playbook_dir }}/../biap-app-ui-front/nginx-replace-with-domain.conf"
        dest: "/home/ubuntu/biap-app-ui-front/nginx.conf"
        owner: "ubuntu"
        group: "ubuntu"
        mode: "0755"

    - name: replace __domain__ with domain name
      replace:
        path: "/home/ubuntu/biap-app-ui-front/nginx.conf"
        regexp: "__domain_name__"
        replace: "{{ domain }}"

    - name: Run docker compose up
      shell: "cd /home/ubuntu/ && sudo docker-compose build && sudo docker-compose up -d"
