---
- name: Update web servers
  hosts: "{{ target }}"
  remote_user: ubuntu

  vars_prompt:
    - name: target
      prompt: enter the hostname which you might have mentioned in host file
      private: no

    - name: domain
      prompt: please enter the domain which will be serving the requests
      private: no

    - name: envtype
      prompt: please enter the env file to copy, we are appending to .env, hence value can be -staging etc
      private: no

  tasks:
    - name: Clone biap-client-node-js
      git:
        repo: "https://github.com/Open-network-for-digital-commerce/biap-client-node-js.git"
        dest: "/home/ubuntu/biap-client-node-js"
        version: "master"
        force: yes

    - name: Clone biap ui
      git:
        repo: "https://github.com/Open-network-for-digital-commerce/biap-app-ui-front.git"
        dest: "/home/ubuntu/biap-app-ui-front"
        version: "master"
        force: yes

    - name: Clone py ondc protocol
      git:
        repo: "https://github.com/sharmasahil0331/py-protocol-layer"
        dest: "/home/ubuntu/py-ondc-protocol"
        version: "dev"
        force: yes

    - name: Copy config directory
      copy:
        src: "{{ playbook_dir }}/../biap-client-node-js/config"
        dest: "/home/ubuntu/biap-client-node-js/"
        owner: "ubuntu"
        group: "ubuntu"
        mode: "0755"

    - name: Copy lets encrypt with domain replaced
      copy:
        src: "{{ playbook_dir }}/../init-letsencrypt.sh"
        dest: "/home/ubuntu/init-letsencrypt.sh"
        owner: "ubuntu"
        group: "ubuntu"
        mode: "0755"

    - name: replace __domain__ with domain name
      replace:
        path: "/home/ubuntu/init-letsencrypt.sh"
        regexp: "__domain_name__"
        replace: "{{ domain }}"

    - name: copy Dockerfile without SSL as dockerfile in biap-app-ui-front
      copy:
        src: "{{ playbook_dir }}/../biap-app-ui-front/Dockerfile"
        dest: "/home/ubuntu/biap-app-ui-front/Dockerfile"
        owner: "ubuntu"
        group: "ubuntu"
        mode: "0755"

    - name: replace __domain__ with in nginx.conf
      replace:
        path: "/home/ubuntu/biap-app-ui-front/nginx-replace-with-domain.conf"
        regexp: "__domain_name__"
        replace: "{{ domain }}"

    - name: copy env file with domain replaced
      copy:
        src: "{{ playbook_dir }}/../.env{{ envtype }}"
        dest: "/home/ubuntu/.env"
        owner: "ubuntu"
        group: "ubuntu"
        mode: "0755"

    - name: replace __domain__ with domain name
      replace:
        path: "/home/ubuntu/.env"
        regexp: "__domain_name__"
        replace: "{{ domain }}"

    - name: Modify .env file
      lineinfile:
        path: .env
        line: ENV_TYPE={{ target }}

    - name: Copy docker-compose file with domain replaced
      copy:
        src: "{{ playbook_dir }}/../docker-compose.yaml"
        dest: "/home/ubuntu/docker-compose.yml"
        owner: "ubuntu"
        group: "ubuntu"
        mode: "0755"

    - name: Run docker compose up
      shell: "cd /home/ubuntu/ && sudo docker-compose build && sudo docker-compose up -d"
      register: out

    - name: Docker-Compose Output
      debug: var=out

    - name: run letsencrypt
      shell: "cd /home/ubuntu/ && sudo ./init-letsencrypt.sh"
